- name: Update system packages
  pacman:
    upgrade: true
- name: Install primary system utilites
  pacman:
    state: present
    with_items:
      - git
      - base-devel
      - cmake
      - linux-headers
      - nano
      - alacritty
      - neofetch # can't forget this core utility
      - ttf-jetbrains-mono-nerd
- name: Check for NVIDIA GPU
  command: lspci -k | grep -A 2 -E "(VGA|3D)"
  register: lspci_output
  ignore_errors: yes
- name: Install NVIDIA drivers
  pacman:
    name: nvidia
    state: present
    when: "'nvidia' in lspci_output.stdout or 'NVIDIA' in lspci_output.stdout"
- name: Configure xorg
  command: nvidia-xconfig
  when: "'nvidia' in lspci_output.stdout or 'NVIDIA' in lspci_output.stdout"
